dist:
  trusty

sudo:
  required

language:
  python

python:
  - 3.6

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"
    - K8S_OPS_REPO_BRANCH=master
    - K8S_OPS_REPO_SLUG=OpenBudget/budgetkey-k8s
    - DOCKER_IMAGE=budgetkey/open-budget-search-api
    - DEPLOY_YAML_UPDATE_FILE=values.auto-updated.yaml
    - DEPLOY_VALUES_CHART_NAME=search-api
    - DEPLOY_VALUES_IMAGE_PROP=image
    - DEPLOY_COMMIT_MESSAGE="automatic update of open-budget-search-api"
    - DEPLOY_GIT_EMAIL=budgetkey-deployer@null.void
    - DEPLOY_GIT_USER=budgetkey-deployer
    - secure: jWcURCkq+Bx+ROkPAcqRA2NV04+I3Egs2hRqIvmE/2JnKlKB7D/Arm3Op+FIchS3qPm0Xq2ZGVHS1lQjVykvLGo4nT8bZpoBvfuGoTR3GhuRE2qnil9eauYplYUxG8K1T3C1zcBR9l2R2OQQbg6tO5xcXsq0pyXIkI63nMUcZiU9GdnfEjsJnLx/dotXXQD9UGStQWOH4hIj/U2PrPSxWkmq6tYSTpLCAfBvzsvbJ5c9zlL1v75NVHGrqsGNc0x33DDZz1jnKWRk7fpwsnnEWlfozgB1REvK3uO3X/R0ZCurnFrrp6XdIMFBVG16Phr8hD/JeoSkN0zL4x78JafJYHjc+TObZER7AUjgUKtxu/yTQ+9Q1kw4B2Dz6ftLd37GkRhlW9PwpXNGqQ/d1iEQzDJWJvvLXSG06V335OYzaa3Zmnu3fkm55TPFQ/VSZKp1gadIhMGC9wo+Z78bqgo+JMlZvNng4jJPO+Y+SSRi1kgys87aApfzglZFQZrgo6HEqLCFH/8FAX0wa4l9US4nyj1ruP8i9uzNAAqGgaPSPPgtr294z402K6m5HCUDO3AIR1IHpB0kcPRsVh8yNloDRwZ1o4kARCjDlDJVFodn+U2irE6xqMzDCP/KoqxCLIZsF6nE6ZE1Ruc3tNIImsMliuyWSvrz7GHBSGuduvrCnHY=
    - secure: L9nwvbpusCaGPHxlvhaEdzvdjpHSOBnZBi7tfh2bH2/AUXzfoqWK5KxKYrG/IEpjUgirweMEdXnTzKj6vLXwXI1RJXq+NqBc5fof3zJQsun/KbwoskT3Ikx1cVBJU5xRtotZTdNDYI+6UEHkWjBvZgM98St5iN1+eXnFtcDMDh3QVeW35igIdPj9YBeHyvI6HeFGDfEwGPuM4QeRP6dzP2PaI42LmxErjruf1wF+mTGJepL93a8/TuaioEP/c9n3/8kk62lX0/8D36iyc3tfv7kCzUL/zDtSAQCHBSuwkIy0iOStjWgStyE6OKBNo6ldTfrqztgVCbxN+CcuY+GkQO/FpmyTyQ/9vZczF3T3lQB60vdgAiOzGqN/LvuWcet9BqM7CWE2fXgdnDdCUrhOqDDMFwBBu+ntiUrrUPslMvA/1djcZWR6JmEtwzNVjrPT5gjae4dBtkUkGefgZKngLivRQADUJqqEp4B85Z6SKaaRWQSpYCd9bi50Qczq1g3GDuDRuL1cRNt1G2ojvZxEOUOVgiPZFsdKVA9S44Ky9NLSskaOelJO7cJ+svW7erFOkCxFcjkn2iDoQ2arF3yofmCVeuESGNDV4rg1ezcZncDfImYwEVZHsVqhF09YkckBdy9VcKa3PIeDr3v/8p+i8wzlvokfrpnO6RaLnoRpi60=
    - secure: fD57Q/TkT9ATkKPMnscZWlrY1p9oygXH3RoP4oOeGTmBQqtWItcwAhm2DrlCBv1UYJ1b5NpbBLs29zkcQJB2yDnCsk8LGLiiaQgCExPPX1An3aEQ5IzKOkzV/Dbky27G0FeCBBUBj3bWmSnb3xJukADpTVjWUYwpeoq+S+uHEKGxM5/858jA+5Q7fVlDybOQp3bThL6j6Ah2ptohyjFBymqYkOVe6ClnSyQ5AqeeDq9gCV6UHi0ptCEkhUSPyKI6MHS6Z+pQfEY8IDxlLFYUf7GoA9LUCtKQyalSCGpPi9Noj40sUuP5VYK7PQmNbkgzZUFeu8nSGvcpb32GNIa5HIjlfd+QKMRP07V3B58SJSCiCbX+zeuXsiWTSaK51YB6bEeMdb8qc+hiuvIyI2Ntq7u6rCRI4C+4V2+Dh/Qu+TDwgOrsQnS6aUwjd4SUS0PQfNKtEgLtniDqOnFpOMatS0iwLj2mAQVKPc/vknCt0JpzRP4Q938+Gyr9ZJJXpq/mKerGeFw0oRc0pe3vQyILCbs9GmU8YoIo029z7eDBE9rVGI/xFUUIRumkwdKp16EzoU5MMiYNlTiZCzo4pzUERTInCcKwdvRKqolWG/sM+x39VYUH0SGQRsor5Ao2jMWiFrO9BcAF7idd5MaoW55vnjyYiuP0lN4xPXHsjKzgh8w=

services:
  - docker

before_install:
  - curl -s https://raw.githubusercontent.com/OpenBudget/budgetkey-k8s/master/apps_travis_script.sh > .travis.sh
  - bash .travis.sh script

install:
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
